version: '3.7'

services:

  cp-client-web:
    environment:
      - NODE_ENV=development
    ports:
      - 4200:4200
    command: npm run _start -- --host 0.0.0.0  --proxy-config ./src/proxy.conf.compose.json
    volumes:
      - ./package.json:/usr/src/app/client-web/package.json
      - ./tsconfig.json:/usr/src/app/client-web/tsconfig.json
      - ./angular.json:/usr/src/app/client-web/angular.json
      - ./src:/usr/src/app/client-web/src
      - ../coinpush-shared/:/usr/src/app/coinpush-shared
       
networks:
  default:
    external:
      name: coinpush-api_cp-net